### ISSUE TITLE
Crash on non-arrow key

### ISSUE THREAD

**Issue by Ivniinvi** [bootstrapworld/wescheme-compiler2012#5]
My game crashes when I press a key other than the arrow keys. It says:
`posn-x: expects a posn as 1st argument, but given: 200 at: line 138, column 27, in bootstrap2012/bootstrap-teachpack`

**Comment by schanzer** [comment]
Can you explain why this is a bug in WeScheme, as opposed to a bug in your game? Without seeing your code, it's impossible to tell.

**Comment by Ivniinvi** [comment]
My Code:
(require bootstrap2012/bootstrap-teachpack)
(define TITLE "Deep Space")
(define TITLE-COLOR "red")
(define BACKGROUND (bitmap/url
"https://media.giphy.com/media/ygAaR0n5RsyAM/giphy.gif"))
(define DANGER (rotate 291.8 (bitmap/url
"http://vignette1.wikia.nocookie.net/chickeninvaders/images/d/d7/Galaga_ship.png")))
(define TARGET (bitmap/url
"http://www.mpcreativedev.com/statics/images/prodotti-sky/skydigitalkey/glow-circle.png"))
(define PLAYER (scale .5 (rotate 270 (bitmap/url
"https://lh6.ggpht.com/h-BTOsLoRJ3ciyCgzDmHt_xQVApn52KDwSg4kusvZNwvicmAH1AtYnv0KsWrhU8qsIE=w300"))))
(define (update-danger x y)  (make-posn (+ x 50) (+ y 20)))
(define (update-target x)  (- x 30))
(define (safe-left? x) (> x -50))
(define (safe-right? x) (< x 690))
(define (onscreen? x)
  (and (safe-left? x)
       (safe-right? x)))
(define (update-player x y key)
  (cond
    [(string=? key "up") (make-posn x (+ y 40))]
    [(string=? key "down") (make-posn x (- y 40))]
    [(string=? key "left") (make-posn (- x  40) y)]
    [(string=? key "right") (make-posn (+ x 40) y)]
    [else y]))
(define *distances-color* "")
(define (line-length a b)
  (cond
    [(> a b) (- a b)]
    [else (- b a)]))
(define (distance px py cx cy)
  (sqrt (+ (sq (line-length px cx))
           (sq (line-length py cy)))))
(define (collide? px py cx cy)
         (< (distance px py cx cy) 50))
(define mystery (rectangle 20 5 "solid" "green"))
(define (update-mystery x)
  (- x 30))
(define game_level (make-game TITLE TITLE-COLOR
                     BACKGROUND
                     DANGER update-danger
                     TARGET update-target
                     PLAYER update-player
                     mystery update-mystery
                     *distances-color* line-length distance
                     collide? onscreen?))
(play game_level)

**Comment by schanzer** [comment]
WeScheme is not crashing - instead, you're getting an _error message_ because your `update-player` code is incorrect. I suggest using the Design Recipe to find out where your mistake lies.
